### PR TITLE
Update RepoToolset to 1.0.0-beta-62615-02

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@tannergooding @livarcocc We are switching all repos to SHA256. See dotnet/roslyn#24820 for background.

**Comment by tmat** [comment]
@livarcocc Yes, we need to update dotnet CLI to later version that has compilers that support signing on non-Windows. This repo has a build time dependency on CLI 1.1.4. Any reason not to update to 2.1.100-preview-007366?

**Comment by tannergooding** [comment]
Updating the version of the SDK we build with should be fine. You will need to update the build.ps1 and build.sh to also install the 1.1 shared framework, however. (Compare https://github.com/dotnet/dotnet-cli-archiver/blob/master/build/build.ps1 with https://github.com/dotnet/CliCommandLineParser/blob/master/build/build.ps1)

**Comment by tmat** [comment]
@tannergooding Could you follow up on this?

**Pull request closed without merging**
