### PR TITLE
Moving to repo-toolset

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
test ci please

**Comment by livarcocc** [comment]
FYI @jonsequitur This aligns this repo with the tooling shared by the other repos under Matt. This is also needed for prod con.

**Comment by tannergooding** [comment]
test ci please

**Comment by tannergooding** [comment]
test Ubuntu16.04 x64 Debug please

**Comment by tannergooding** [comment]
The two failing jobs were the existing CI without the groovy changes.

The three passing jobs are the updated ones, with the groovy changes (Windows_NT x64 Debug actually passed, but didn't update on the GitHub side for some reason).

**Pull request merged**
