### PR TITLE
Enable signed internal builds

### PR DESCRIPTION
**Pull request by chcosta**
Internal builds are currently broken without this change until they are moved from devdiv to dnceng.

FYI @mmitche

### CODE REVIEW

**Comment by mmitche** [comment]
@chcosta Should we just move them?

**Comment by chcosta** [comment]
Yes, that's my preference, but I also wanted to highlight how to work around the issue if moving is not an immediate options.  I'm completely ok with not merging this.

**Comment by livarcocc** [comment]
I would prefer to just move it.

**Comment by chcosta** [comment]
Great!

**Pull request closed without merging**
